<a href="https://colab.research.google.com/github/manyasachdeva27/MACHINE-LEARNING/blob/main/Encoding_Categorical_data(Ordinal_encoding).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('/content/customer.csv')

In [ ]:
df.sample(5)

    age  gender   review education purchased
33   89  Female     Good        PG       Yes
10   98  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
32   92    Male  Average        UG       Yes
16   59    Male     Poor        UG       Yes

In [ ]:
df=df.iloc[:,2:]

In [ ]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=0)

In [ ]:
pd.DataFrame(x_train)

      0    1
0   1.0  0.0
1   2.0  1.0
2   2.0  0.0
3   0.0  1.0
4   1.0  1.0
5   2.0  1.0
6   2.0  0.0
7   2.0  0.0
8   1.0  2.0
9   0.0  2.0
10  2.0  2.0
11  0.0  2.0
12  0.0  2.0
13  2.0  2.0
14  1.0  0.0
15  0.0  1.0
16  2.0  0.0
17  0.0  2.0
18  0.0  1.0
19  1.0  1.0
20  0.0  1.0
21  2.0  2.0
22  1.0  1.0
23  1.0  2.0
24  2.0  2.0
25  2.0  1.0
26  0.0  0.0
27  0.0  0.0
28  1.0  1.0
29  1.0  1.0
30  1.0  2.0
31  0.0  0.0
32  2.0  0.0
33  1.0  2.0
34  2.0  0.0
35  2.0  0.0
36  1.0  0.0
37  0.0  1.0
38  1.0  0.0
39  0.0  2.0

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

# Re-create x_train and x_test from the original df to ensure they contain string values
x_train,x_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.2,random_state=0)

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:

oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
x_train=oe.transform(x_train)
x_test=oe.transform(x_test)

In [ ]:
x_train

array([[2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])