<a href="https://colab.research.google.com/github/manyasachdeva27/MACHINE-LEARNING/blob/main/KNN_Imputer_(Handling_Missing_Values).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer, SimpleImputer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('train.csv',usecols=['Age','Pclass','Fare','Survived'])

In [ ]:
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [ ]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [ ]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

In [ ]:
knn=KNNImputer(n_neighbors=2,weights='uniform') #also weights=distance for better results

X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [ ]:
pd.DataFrame(X_train_trf,columns=['PClass','Age','Fare'])

     PClass   Age      Fare
0       1.0  40.0   27.7208
1       3.0   4.0   16.7000
2       3.0  47.0    9.0000
3       3.0   9.0   31.3875
4       3.0  20.0    9.8458
..      ...   ...       ...
707     3.0  30.0    8.6625
708     3.0  30.5    8.7125
709     1.0  71.0   49.5042
710     1.0  28.0  221.7792
711     1.0  56.5   25.9250

[712 rows x 3 columns]

In [ ]:
lr=LogisticRegression()

lr.fit(X_train_trf,y_train)

LogisticRegression()

In [ ]:
y_pred=lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7094972067039106